insert into Cities (Name) values ('Liukou');
insert into Cities (Name) values ('Irákleion');
insert into Cities (Name) values ('San Javier');
insert into Cities (Name) values ('Hāfizābād');
insert into Cities (Name) values ('Tinghir');
insert into Cities (Name) values ('Temara');
insert into Cities (Name) values ('Candelaria');
insert into Cities (Name) values ('Auna');
insert into Cities (Name) values ('Sydney');
insert into Cities (Name) values ('Chincha Baja');
insert into Cities (Name) values ('Kněžpole');
insert into Cities (Name) values ('Cabaiguán');
insert into Cities (Name) values ('Bibrka');
insert into Cities (Name) values ('Zakan-Yurt');
insert into Cities (Name) values ('Upper San Mateo');
insert into Cities (Name) values ('Hultsfred');
insert into Cities (Name) values ('Luozhuang');
insert into Cities (Name) values ('Желино');
insert into Cities (Name) values ('Irosin');
insert into Cities (Name) values ('Chiquinquirá');
insert into Cities (Name) values ('Cincinnati');
insert into Cities (Name) values ('Kuncen');
insert into Cities (Name) values ('Miguel Pereira');
insert into Cities (Name) values ('Karangan');
insert into Cities (Name) values ('Matabao');
insert into Cities (Name) values ('Shimanovsk');
insert into Cities (Name) values ('Uzyn');
insert into Cities (Name) values ('Novopokrovka');
insert into Cities (Name) values ('Yamaguchi-shi');
insert into Cities (Name) values ('Badar');
insert into Cities (Name) values ('Coulommiers');
insert into Cities (Name) values ('Nanyang');
insert into Cities (Name) values ('Olocuilta');
insert into Cities (Name) values ('Huayana');
insert into Cities (Name) values ('Cookshire-Eaton');
insert into Cities (Name) values ('Gosë e Madhe');
insert into Cities (Name) values ('Lidingö');
insert into Cities (Name) values ('Johanneshov');
insert into Cities (Name) values ('Al Muwayh');
insert into Cities (Name) values ('Bridgewater');
insert into Cities (Name) values ('Al Fandaqūmīyah');
insert into Cities (Name) values ('Mokolo');
insert into Cities (Name) values ('Luksuhin');
insert into Cities (Name) values ('Zmijavci');
insert into Cities (Name) values ('Potęgowo');
insert into Cities (Name) values ('Hanshou');
insert into Cities (Name) values ('Sabhā');
insert into Cities (Name) values ('Ramat Gan');
insert into Cities (Name) values ('Thala');
insert into Cities (Name) values ('Bojszowy Nowe');
