insert into Streets (Name) values ('Monterey');
insert into Streets (Name) values ('Lotheville');
insert into Streets (Name) values ('Marcy');
insert into Streets (Name) values ('Fieldstone');
insert into Streets (Name) values ('Debra');
insert into Streets (Name) values ('New Castle');
insert into Streets (Name) values ('Mandrake');
insert into Streets (Name) values ('Dakota');
insert into Streets (Name) values ('Straubel');
insert into Streets (Name) values ('Prentice');
insert into Streets (Name) values ('Blaine');
insert into Streets (Name) values ('Vermont');
insert into Streets (Name) values ('Jay');
insert into Streets (Name) values ('Oxford');
insert into Streets (Name) values ('Glendale');
insert into Streets (Name) values ('Bobwhite');
insert into Streets (Name) values ('Golden Leaf');
insert into Streets (Name) values ('Lakeland');
insert into Streets (Name) values ('Fair Oaks');
insert into Streets (Name) values ('Lake View');
insert into Streets (Name) values ('Lakewood');
insert into Streets (Name) values ('Bultman');
insert into Streets (Name) values ('Arkansas');
insert into Streets (Name) values ('Sunbrook');
insert into Streets (Name) values ('Glacier Hill');
insert into Streets (Name) values ('Bowman');
insert into Streets (Name) values ('Muir');
insert into Streets (Name) values ('Scott');
insert into Streets (Name) values ('Straubel');
insert into Streets (Name) values ('Di Loreto');
insert into Streets (Name) values ('Swallow');
insert into Streets (Name) values ('Pine View');
insert into Streets (Name) values ('Packers');
insert into Streets (Name) values ('Jackson');
insert into Streets (Name) values ('Derek');
insert into Streets (Name) values ('Tennessee');
insert into Streets (Name) values ('Packers');
insert into Streets (Name) values ('Mesta');
insert into Streets (Name) values ('Park Meadow');
insert into Streets (Name) values ('Oriole');
insert into Streets (Name) values ('Loftsgordon');
insert into Streets (Name) values ('Kingsford');
insert into Streets (Name) values ('Sachtjen');
insert into Streets (Name) values ('Saint Paul');
insert into Streets (Name) values ('American');
insert into Streets (Name) values ('Randy');
insert into Streets (Name) values ('Russell');
insert into Streets (Name) values ('Kim');
insert into Streets (Name) values ('Mitchell');
insert into Streets (Name) values ('3rd');
insert into Streets (Name) values ('Columbus');
insert into Streets (Name) values ('Westport');
insert into Streets (Name) values ('Fairfield');
insert into Streets (Name) values ('Old Shore');
insert into Streets (Name) values ('Oxford');
insert into Streets (Name) values ('Corry');
insert into Streets (Name) values ('Lake View');
insert into Streets (Name) values ('Crownhardt');
insert into Streets (Name) values ('Nobel');
insert into Streets (Name) values ('Sycamore');
insert into Streets (Name) values ('Independence');
insert into Streets (Name) values ('Barby');
insert into Streets (Name) values ('Lake View');
insert into Streets (Name) values ('Becker');
insert into Streets (Name) values ('Superior');
insert into Streets (Name) values ('Main');
insert into Streets (Name) values ('Meadow Valley');
insert into Streets (Name) values ('Chinook');
insert into Streets (Name) values ('Roth');
insert into Streets (Name) values ('Gerald');
insert into Streets (Name) values ('Moland');
insert into Streets (Name) values ('Bultman');
insert into Streets (Name) values ('Waywood');
insert into Streets (Name) values ('Ridgeview');
insert into Streets (Name) values ('Porter');
insert into Streets (Name) values ('Anthes');
insert into Streets (Name) values ('Mayer');
insert into Streets (Name) values ('Forster');
insert into Streets (Name) values ('Hoepker');
insert into Streets (Name) values ('Rigney');
insert into Streets (Name) values ('Southridge');
insert into Streets (Name) values ('Raven');
insert into Streets (Name) values ('Swallow');
insert into Streets (Name) values ('Nevada');
insert into Streets (Name) values ('Vera');
insert into Streets (Name) values ('Barnett');
insert into Streets (Name) values ('Stuart');
insert into Streets (Name) values ('Packers');
insert into Streets (Name) values ('Havey');
insert into Streets (Name) values ('Roth');
insert into Streets (Name) values ('Chinook');
insert into Streets (Name) values ('Independence');
insert into Streets (Name) values ('Bartelt');
insert into Streets (Name) values ('Southridge');
insert into Streets (Name) values ('Commercial');
insert into Streets (Name) values ('Haas');
insert into Streets (Name) values ('Springview');
insert into Streets (Name) values ('Michigan');
insert into Streets (Name) values ('Comanche');
insert into Streets (Name) values ('Sachtjen');
